server {
    listen 80;

    # FRONTEND (Next.js)
    location / {
        proxy_pass http://fe:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # (optional) Laravel langsung tanpa /api
    location /backend/ {
        proxy_pass http://be:80/;
    }
}